ACCOUNT_ACTIVATION_DAYS = 7
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = "test.shmarget@yandex.ru"
EMAIL_HOST_PASSWORD = "!123qwerty"
EMAIL_USE_SSL = True

SERVER_EMAIL = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

